image: tonipes/sfml-docker:0.2

before_script:
  - git submodule update --init --recursive

stages:
  - build
  - make
  - test
  - cleanup

cache:
  untracked: true
  paths:
    - build

build:
  stage: build
  script:
    - ./build.sh

make:
  stage: make
  script:
    - ./build.sh make

unit_test:
  # TODO: Run tests
  stage: test
  script:
    - echo "Run unit tests here"

run_test:
  stage: test
  script:
    - ./build.sh testrun

cleanup_build:
  stage: cleanup
  script:
    - ./build.sh clean
